apiVersion: v1 
kind: Pod
metadata: 
  name: service_a
  labels: 
    app: service_a
spec: 
  containers: 
  - name: service_a 
    image: israelerlan1/service_a
    imagePullPolicy: Always
    ports:
      containerPort: 8000 
