apiVersion: v1
kind: Pod
metadata:
  name: api-b
  labels:
    app: api-b
spec:
  containers:
  - name: api-b
    image: sdbr1234/ip-geolocation:2.0
    imagePullPolicy: Always
    ports:
    - containerPort: 8080